--===========================================================================================================
-- Magnitude Exploration: total sales, quantity, orders, etc., by a varianble (country, customer, day, etc.)
--===========================================================================================================

-- Find total customers by countries
SELECT	
	country, 
	COUNT(country) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers;

--Find total customers by gender
SELECT
	gender,
	COUNT(customer_key) AS total_cusomers
FROM gold.dim_customers
GROUP BY gender;

-- Find total products by category
SELECT
	category,
	COUNT(product_key) AS total_products
FROM gold.dim_products 
GROUP BY category
ORDER BY total_products DESC;

-- What is the average costs in each category?
SELECT
	category,
	AVG(cost) AS avg_cost
FROM gold.dim_products 
GROUP BY category
ORDER BY avg_cost DESC;

-- What is the total revenue generated for each category?
SELECT
	dp.category,
	SUM(fs.sales_amount) AS total_revenue
FROM gold.fact_sales AS fs
INNER JOIN gold.dim_products AS dp
ON fs.product_key = dp.product_key
GROUP BY dp.category
ORDER BY total_revenue DESC;

-- Find total revenue is generated by each customer
SELECT
	dc.customer_key,
	dc.first_name,
	dc.last_name,
	SUM(fs.sales_amount) AS total_revenue
FROM gold.fact_sales AS fs
INNER JOIN gold.dim_customers AS dc
ON fs.customer_key = dc.customer_key
GROUP BY dc.customer_key, dc.first_name, dc.last_name
ORDER BY total_revenue DESC;

--What is the distribution of sold items
SELECT
	dc.country,
	SUM(fs.quantity) AS total_sold_items
FROM gold.fact_sales AS fs
INNER JOIN gold.dim_customers AS dc
ON fs.customer_key = dc.customer_key
GROUP BY dc.country
ORDER BY total_sold_items DESC;
